### ISSUE TITLE
Undefined errors when compiling BioSignalsPlux C++ SDK

### ISSUE THREAD

**Issue by pcha75** [biosignalsplux/cpp-samples#1]
Hello, 

hope everybody is doing well. 
My team recently bought an EOG sensor from BioSignalsPlux: https://biosignalsplux.com/products/sensors/electrooculography.html. The package is on its way, and I am working on how to integrate it in our application. 
I saw that you uploaded an SDK to communicate with the EOG: https://github.com/biosignalsplux/cpp-samples. I downloaded it and try to run the example (even though I still can not get my hands on the actual sensor). I have an issue when I compile simpleApp.cpp example. I have some linking errors such as: `C:\Users\eyebrain\dev\eog\simpleApp.cpp:-1: error: undefined reference to Plux::BaseDev::findDevices(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)`. 
So I was wondering if there was any issue with some updates of the precompiled (.lib) files that you distribute with your C++ interface...

Thank you!

**Comment by DFNOsorio** [comment]
Dear user,

There are no reported issues, but I will look into it. 

Best regards

**Comment by pcha75** [comment]
To be more precise, I managed to compile the C++ SDK using MVS2019 compiler, but when it comes to compite using MinGW, the compiler outputs these undefined errors.

**Comment by DFNOsorio** [comment]
We only provide libs for the visual studio compiler, which are not compatible with MinGW or other compilers.

**Comment by pcha75** [comment]
I have another question: in your repository, what do MD and MT mean? For instance, in ./Win-VS2017/64-bits/Release_MT/.
